### ISSUE TITLE
Will be adding support for queries via POST

### ISSUE THREAD

**Issue by optmsp** [Anteris-Dev/autotask-client-generator#14]
I'll be adding support for queries via POST. Right now you only support queries via GET. If there is anything I should know, including any "gotches" that snagged you if you went down this road already, please let me know.

I can see this impacts *Service and QueryBuilder.

**Comment by aidan-casey** [comment]
@optmsp - The only problem I am aware of is with caching such requests (which we are not doing in the current version but are planning for the next). Unfortunately, I am a little busy at this moment, but would accept a PR that implements this.

**Comment by optmsp** [comment]
So when I write this up, my thoughts are that we use a POST anytime we do an "in" comparison or compound comparisons.

We could build a get string if Items < 500, but 99.9% that will exceed GET maxlen with even 200 Items in a comparison.

Thoughts?

I mean, heck, even a GET query on TicketNote could have a comparison that results in strlen(description) > 2048 or whatever the GET maxlen is.. ?

Maybe the logic would be:

If comparisonOp is IN or If UrlHost+comparisonStrLen >= MaxHttpGetLen Then USE POST Else USE GET

Or perhaps ditch GET forever except findByID..

I wonder if there is a performance advantage to using GET?

**Comment by samdark** [comment]
Done. See https://github.com/Anteris-Dev/autotask-client-generator/pull/15
